KnpMenuBundle; update to git pre-commit hook
php-cs-fixer

Conflicts solved

diff --git a/app/config/git-hooks/pre-commit b/app/config/git-hooks/pre-commit
--- a/app/config/git-hooks/pre-commit
+++ b/app/config/git-hooks/pre-commit
@@ -1,39 +1,131 @@
-#!/bin/sh
+#!/bin/bash
 
 # Redirect output to stderr.
 exec 1>&2
 
-# check that cs fixer is installed, otherwise dissalow commits
-if [ ! -e vendor/bin/php-cs-fixer ]
+noErrors="Unable to make commits without checking the code for errors!"
+
+# check that cs fixer is installed, otherwise deny commits
+if [ ! -e vendor/fabpot/php-cs-fixer/php-cs-fixer ]
 then
-    echo "Unable to make commits without checking the code for errors!"
-    echo "php-cs-fixer must be installed in vendor/bin"
+    echo $noErrors
+    echo "php-cs-fixer must be installed in vendor/fabpot/php-cs-fixer/php-cs-fixer"
     echo "in order to install it, run \"composer install --dev\""
     exit 1
 fi
 
-# check that phpunit is installed, otherwise dissalow commits
-if [ ! -e vendor/bin/phpunit ]
+jsLint=`which jslint`
+if [ $? != 0 ] || [ ! -e $jsLint ]
 then
-    echo "Unable to make commits without checking the code for errors!"
-    echo "phpunit must be installed in vendor/bin"
-    echo "in order to install it, run \"composer install --dev\""
+    echo $noErrors
+    echo "jslint must be installed globally"
+    echo "To install jslint run \"npm install -g jslint\""
+    echo "Note that you may need to run npm install with sudo, based on your system setup."
     exit 1
 fi
 
-# if phpunit does not exist, copy the default dist file
-if [ ! -e phpunit.xml ]
+# run jslint
+jsFilesWithError=()
+jsModifiedFiles=`git status | grep ".js$" | grep -v 'renamed: ' | grep -v 'deleted: ' | cut -d" " -f4`
+jsRenamedFiles=`git status | grep ".js$" | grep 'renamed: ' | cut -d" " -f7`
+jsFiles=`echo $jsModifiedFiles $jsRenamedFiles |tr " " "\n" | sort -u`
+
+if [ ${#jsFiles[@]} != 0 ]; then echo "Checking JS files for standards:"; fi
+for file in $jsFiles;
+do
+    $jsLint --config . $file > /dev/null 2>&1;
+    if [ $? != 0 ]
+    then
+        echo -e "\033[0;31m\t$file\033[0m"
+        jsFilesWithError+=($file)
+    else
+        echo -e "\033[0;32m\t$file\033[0m"
+    fi
+done
+
+if [ ${#jsFilesWithError[@]} != 0 ]
 then
-    cp phpunit.xml.dist phpunit.xml
+    echo -e "\033[0;31mPlease fix the JS syntax errors from the files marked with red.\033[0m"
 fi
 
-# run phpunit test
-CS_TEST=`vendor/bin/phpunit -c . src/TSS/CoreBundle/Tests/CodingStandardsTest.php`
-if [ $? != 0 ]
+# run lint:twig
+twigFilesWithError=()
+twigModifiedFiles=`git status | grep ".twig$" | grep -v 'renamed: ' | grep -v 'deleted: ' | cut -d" " -f4`
+twigRenamedFiles=`git status | grep ".twig$" | grep 'renamed: ' | cut -d" " -f7`
+twigFiles=`echo $twigModifiedFiles $twigRenamedFiles |tr " " "\n" | sort -u`
+
+if [ ${#twigFiles[@]} != 0 ]; then echo "Checking twig files for standards:"; fi
+for file in $twigFiles;
+do
+    bin/console lint:twig $file > /dev/null 2>&1;
+    if [ $? != 0 ]
+    then
+        echo -e "\033[0;31m\t$file\033[0m"
+        twigFilesWithError+=($file)
+    else
+        echo -e "\033[0;32m\t$file\033[0m"
+    fi
+done
+
+if [ ${#twigFilesWithError[@]} != 0 ]
 then
-    echo "There are coding standard errors!"
-    echo "Please fix them in order to be able to make commits!"
-    echo ""
-    echo $CS_TEST
+    echo -e "\033[0;31mPlease fix the twig syntax errors from the files marked with red.\033[0m"
+fi
+
+# run lint:yml
+ymlFilesWithError=()
+ymlModifiedFiles=`git status | grep ".yml$" | grep -v 'renamed: ' | grep -v 'deleted: ' | cut -d" " -f4`
+ymlRenamedFiles=`git status | grep ".yml$" | grep 'renamed: ' | cut -d" " -f7`
+ymlFiles=`echo $ymlModifiedFiles $ymlRenamedFiles |tr " " "\n" | sort -u`
+
+if [ ${#ymlFiles[@]} != 0 ]; then echo "Checking yml files for standards:"; fi
+for file in $ymlFiles;
+do
+    bin/console lint:yaml $file > /dev/null 2>&1;
+    if [ $? != 0 ]
+    then
+        echo -e "\033[0;31m\t$file\033[0m"
+        ymlFilesWithError+=($file)
+    else
+        echo -e "\033[0;32m\t$file\033[0m"
+    fi
+done
+
+if [ ${#ymlFilesWithError[@]} != 0 ]
+then
+    echo -e "\033[0;31mPlease fix the yml syntax errors from the files marked with red.\033[0m"
+fi
+
+# run php-cs-fixer test
+phpFilesWithError=()
+phpModifiedFiles=`git status | grep ".php$" | grep -v 'renamed: ' | grep -v 'deleted: ' | cut -d" " -f4`
+phpRenamedFiles=`git status | grep ".php$" | grep 'renamed: ' | cut -d" " -f7`
+phpFiles=`echo $phpModifiedFiles $phpRenamedFiles |tr " " "\n" | sort -u`
+
+if [ ! -z "$phpFiles" ]; then echo -e "Checking PHP coding standards:"; fi
+
+for file in $phpFiles;
+do
+    vendor/fabpot/php-cs-fixer/php-cs-fixer fix -vvv --level=symfony --dry-run $file > /dev/null 2>&1;
+    if [ $? != 0 ]
+    then
+        echo -e "\033[0;31m\t$file\033[0m"
+        phpFilesWithError+=($file)
+    else
+        echo -e "\033[0;32m\t$file\033[0m"
+    fi
+done
+
+if [ ${#phpFilesWithError[@]} != 0 ]
+then
+    echo -e "\n\033[0;31mThere are coding standard errors!"
+    echo "Please fix them in order to be able to make commits!\n"
+    echo -e "\033[0mTo fix all the files automatically, you can run the following command:"
+    echo -e "\033[0;37m\tgit status -s | grep \"\.php$\" | cut -d\" \" -f3 | xargs -L1 php-cs-fixer fix --level=symfony -vvv\033[0m"
+    exit 1
+fi
+
+if [ ${#jsFilesWithError[@]} != 0 ] || [ ${#twigFilesWithError[@]} != 0 ] || [ ${#ymlFilesWithError[@]} != 0 ]
+then
     exit 1
 fi
